image: "python:3.8"

stages:
  - static analysis
  - test
  - build

before_script:
  - pip install -r requirements.pip

flake8:
  stage: static analysis
  script:
    - flake8 --max-line-length=120 \
      --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,venv/* \

test:
  stage: test
  script:
    - pytest
  artifacts:
    when: always
    reports:
      junit: test_rep.xml

test deploy:
  stage: test
  script: ./deploy_to_test_pypi.sh
  only:
    refs:
      - dev

build:
  stage: build
  script: ./deploy_to_pypi.sh
  only:
    refs:
    - stable

